sudo: false

env:
  global:
    - KERNEL_CLASS=DTL\\Bundle\\PhpcrMigrations\\Tests\\Resources\\App\\AppKernel

matrix:
  include:
    - language: php
      php: 5.6
      env:
        - SYMFONY_VERSION=2.8.*
        - MONOLOG_VERSION=^1.0

    - language: php
      php: 5.6
      env:
        - SYMFONY_VERSION=3.4.*
        - MONOLOG_VERSION=^1.0

    - language: php
      php: 7.0
      env:
        - SYMFONY_VERSION=3.4.*
        - MONOLOG_VERSION=^1.0

    - language: php
      php: 7.1
      env:
        - SYMFONY_VERSION=4.0.*
        - MONOLOG_VERSION=^1.0

    - language: php
      php: 7.2
      env:
        - SYMFONY_VERSION=4.0.*
        - MONOLOG_VERSION=^1.0

    - language: php
      php: 7.2
      env:
        - SYMFONY_VERSION=4.1.*
        - MONOLOG_VERSION=^1.0

    - language: php
      php: 7.3
      env:
        - SYMFONY_VERSION=4.4.*
        - MONOLOG_VERSION=^1.0

    - language: php
      php: 7.4
      env:
        - SYMFONY_VERSION=5.0.*
        - MONOLOG_VERSION=^2.0

before_script:
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer require monolog/monolog:${MONOLOG_VERSION} --no-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update -o
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: vendor/bin/simple-phpunit
