name: CI

on:
    pull_request:
    push:
        branches:
        - '[0-9]+.x'
        - '[0-9]+.[0-9]+'
        - '[0-9]+.[0-9]+.x'

jobs:
    php:
        name: "PHP ${{ matrix.php-version }} Symfony ${{ matrix.symfony-version }}"
        runs-on: ubuntu-latest

        env:
            KERNEL_CLASS: PHPCR\PhpcrMigrationsBundle\Tests\Resources\App\AppKernel

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '8.1'
                      symfony-version: '^5.4'

                    - php-version: '8.1'
                      symfony-version: '6.0.*'

                    - php-version: '8.1'
                      symfony-version: '^6.0'

                    - php-version: '8.2'

                    - php-version: '8.3'

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: ctype, iconv, mysql
                  ini-values: memory_limit=-1
                  coverage: none

            - name: Add additional packages
              run: |
                  composer require symfony/symfony:${{ matrix.symfony-version }} --no-update
              if: ${{ matrix.symfony-version }}

            - name: Install composer dependencies
              uses: ramsey/composer-install@v3

            - name: Prepare phpcr odm doctrine dbal
              run: vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

            - name: Run tests
              run: vendor/bin/simple-phpunit
